[platformio]
src_dir = src

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
monitor_filters = esp32_exception_decoder, colorize
board_upload.wait_for_upload_port = true
